// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package bdaybot // import "github.com/j-fuentes/bdaybot-slack/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GoogleSheet struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleSheet) Reset()         { *m = GoogleSheet{} }
func (m *GoogleSheet) String() string { return proto.CompactTextString(m) }
func (*GoogleSheet) ProtoMessage()    {}
func (*GoogleSheet) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_474f314d8c30e1a7, []int{0}
}
func (m *GoogleSheet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleSheet.Unmarshal(m, b)
}
func (m *GoogleSheet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleSheet.Marshal(b, m, deterministic)
}
func (dst *GoogleSheet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleSheet.Merge(dst, src)
}
func (m *GoogleSheet) XXX_Size() int {
	return xxx_messageInfo_GoogleSheet.Size(m)
}
func (m *GoogleSheet) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleSheet.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleSheet proto.InternalMessageInfo

func (m *GoogleSheet) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Calendar struct {
	// Types that are valid to be assigned to Calendar:
	//	*Calendar_GoogleSheet
	Calendar             isCalendar_Calendar `protobuf_oneof:"calendar"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Calendar) Reset()         { *m = Calendar{} }
func (m *Calendar) String() string { return proto.CompactTextString(m) }
func (*Calendar) ProtoMessage()    {}
func (*Calendar) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_474f314d8c30e1a7, []int{1}
}
func (m *Calendar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calendar.Unmarshal(m, b)
}
func (m *Calendar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calendar.Marshal(b, m, deterministic)
}
func (dst *Calendar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calendar.Merge(dst, src)
}
func (m *Calendar) XXX_Size() int {
	return xxx_messageInfo_Calendar.Size(m)
}
func (m *Calendar) XXX_DiscardUnknown() {
	xxx_messageInfo_Calendar.DiscardUnknown(m)
}

var xxx_messageInfo_Calendar proto.InternalMessageInfo

type isCalendar_Calendar interface {
	isCalendar_Calendar()
}

type Calendar_GoogleSheet struct {
	GoogleSheet *GoogleSheet `protobuf:"bytes,1,opt,name=google_sheet,json=googleSheet,oneof"`
}

func (*Calendar_GoogleSheet) isCalendar_Calendar() {}

func (m *Calendar) GetCalendar() isCalendar_Calendar {
	if m != nil {
		return m.Calendar
	}
	return nil
}

func (m *Calendar) GetGoogleSheet() *GoogleSheet {
	if x, ok := m.GetCalendar().(*Calendar_GoogleSheet); ok {
		return x.GoogleSheet
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Calendar) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Calendar_OneofMarshaler, _Calendar_OneofUnmarshaler, _Calendar_OneofSizer, []interface{}{
		(*Calendar_GoogleSheet)(nil),
	}
}

func _Calendar_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Calendar)
	// calendar
	switch x := m.Calendar.(type) {
	case *Calendar_GoogleSheet:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GoogleSheet); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Calendar.Calendar has unexpected type %T", x)
	}
	return nil
}

func _Calendar_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Calendar)
	switch tag {
	case 1: // calendar.google_sheet
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoogleSheet)
		err := b.DecodeMessage(msg)
		m.Calendar = &Calendar_GoogleSheet{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Calendar_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Calendar)
	// calendar
	switch x := m.Calendar.(type) {
	case *Calendar_GoogleSheet:
		s := proto.Size(x.GoogleSheet)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OAuth2 struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuth2) Reset()         { *m = OAuth2{} }
func (m *OAuth2) String() string { return proto.CompactTextString(m) }
func (*OAuth2) ProtoMessage()    {}
func (*OAuth2) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_474f314d8c30e1a7, []int{2}
}
func (m *OAuth2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuth2.Unmarshal(m, b)
}
func (m *OAuth2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuth2.Marshal(b, m, deterministic)
}
func (dst *OAuth2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth2.Merge(dst, src)
}
func (m *OAuth2) XXX_Size() int {
	return xxx_messageInfo_OAuth2.Size(m)
}
func (m *OAuth2) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth2.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth2 proto.InternalMessageInfo

func (m *OAuth2) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *OAuth2) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type Config struct {
	Calendar             *Calendar `protobuf:"bytes,1,opt,name=calendar" json:"calendar,omitempty"`
	Oauth2               *OAuth2   `protobuf:"bytes,2,opt,name=oauth2" json:"oauth2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_474f314d8c30e1a7, []int{3}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetCalendar() *Calendar {
	if m != nil {
		return m.Calendar
	}
	return nil
}

func (m *Config) GetOauth2() *OAuth2 {
	if m != nil {
		return m.Oauth2
	}
	return nil
}

func init() {
	proto.RegisterType((*GoogleSheet)(nil), "bdaybot.GoogleSheet")
	proto.RegisterType((*Calendar)(nil), "bdaybot.Calendar")
	proto.RegisterType((*OAuth2)(nil), "bdaybot.OAuth2")
	proto.RegisterType((*Config)(nil), "bdaybot.Config")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_474f314d8c30e1a7) }

var fileDescriptor_config_474f314d8c30e1a7 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x29, 0x48, 0x21, 0xbd, 0x04, 0x01, 0x16, 0x43, 0x25, 0x06, 0x50, 0x18, 0x60, 0x89,
	0x83, 0xc2, 0x84, 0x98, 0x68, 0x07, 0xfe, 0x2c, 0x88, 0x74, 0x63, 0x29, 0x8e, 0x73, 0x75, 0x0c,
	0x26, 0xae, 0x12, 0x7b, 0xe0, 0xdb, 0xa3, 0x38, 0x26, 0xed, 0x66, 0xbf, 0xfb, 0xe9, 0xdd, 0x7b,
	0x07, 0x31, 0xd7, 0xcd, 0x5a, 0x0a, 0xba, 0x69, 0xb5, 0xd1, 0xe4, 0xb0, 0xac, 0xd8, 0x6f, 0xa9,
	0x4d, 0x72, 0x01, 0xd1, 0x93, 0xd6, 0x42, 0xe1, 0xb2, 0x46, 0x34, 0xe4, 0x04, 0x0e, 0x6c, 0xab,
	0x66, 0x93, 0xcb, 0xc9, 0xcd, 0xb4, 0xe8, 0x9f, 0xc9, 0x3b, 0x84, 0x0b, 0xa6, 0xb0, 0xa9, 0x58,
	0x4b, 0xee, 0x21, 0x16, 0x0e, 0x5e, 0x75, 0x3d, 0xed, 0xb0, 0x28, 0x3f, 0xa3, 0xde, 0x8c, 0xee,
	0x38, 0x3d, 0xef, 0x15, 0x91, 0xd8, 0x7e, 0xe7, 0x00, 0x21, 0xf7, 0x36, 0xc9, 0x2b, 0x04, 0x6f,
	0x8f, 0xd6, 0xd4, 0x39, 0x39, 0x87, 0x29, 0x57, 0x12, 0x1b, 0xb3, 0x92, 0x95, 0x5f, 0x1a, 0x0e,
	0xc2, 0x4b, 0x45, 0xae, 0xe0, 0xc8, 0x0f, 0x3b, 0xe4, 0x2d, 0x9a, 0xd9, 0xbe, 0x03, 0xe2, 0x41,
	0x5c, 0x3a, 0x2d, 0xf9, 0x84, 0x60, 0xe1, 0x8a, 0x91, 0x74, 0xbb, 0xc1, 0x07, 0x3b, 0x1d, 0x83,
	0xfd, 0x37, 0x28, 0x46, 0x84, 0x5c, 0x43, 0xa0, 0x59, 0x1f, 0xc2, 0xd9, 0x46, 0xf9, 0xf1, 0x08,
	0x0f, 0xd9, 0x0a, 0x3f, 0x9e, 0xdf, 0x7e, 0x50, 0x21, 0x4d, 0x6d, 0x4b, 0xca, 0xf5, 0x4f, 0xf6,
	0x95, 0xae, 0x2d, 0x36, 0x06, 0xbb, 0xcc, 0xe3, 0x69, 0xa7, 0x18, 0xff, 0xce, 0xd8, 0x46, 0x3e,
	0x78, 0xa5, 0x0c, 0xdc, 0x8d, 0xef, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xac, 0x53, 0xfd, 0xad,
	0x73, 0x01, 0x00, 0x00,
}
